name: test docker build

on:
  push:
    paths-ignore:
      - "README.md"
      - "*/**/*.html"
  pull_request:
  workflow_dispatch:
  
  
jobs:
  docs:
    runs-on: "ubuntu-latest"
    
    steps:
      - name: Checkout repository code
        uses: actions/checkout@v3
        
      - name: Build Docker image
        run: |
          docker build -t wooster-trading-systems .
          
