name: cli docs

on:
  push:
    paths:
      - "cli.py"
  workflow_dispatch:
  
  
jobs:
  docs:
    runs-on: "ubuntu-latest"
    
    steps:
      - name: Checkout repository code
        uses: actions/checkout@v3
        
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install TA-Lib
        run: |
          sudo apt update && sudo apt upgrade -y && sudo apt autoremove -y
          sudo apt install wget -y
          sudo add-apt-repository ppa:deadsnakes/ppa -y
          sudo apt-get install build-essential -y
          sudo apt install python3.10-dev -y
          sudo apt-get install python3-dev -y
          wget http://prdownloads.sourceforge.net/ta-lib/ta-lib-0.4.0-src.tar.gz
          tar -xzf ta-lib-0.4.0-src.tar.gz
          cd ta-lib
          wget 'http://git.savannah.gnu.org/gitweb/?p=config.git;a=blob_plain;f=config.guess;hb=HEAD' -O './config.guess'
          wget 'http://git.savannah.gnu.org/gitweb/?p=config.git;a=blob_plain;f=config.sub;hb=HEAD' -O './config.sub'
          ./configure --prefix=/usr
          make
          sudo make install
          pip install ta-lib
        
      - name: Setup pip and typer-cli
        run: |
          pip install -U pip wheel
          pip install typer-cli
          
      - name: Install project dependencies
        run: |
          sed -i "/typer==0.6.1/d" requirements.txt
          pip install -r requirements.txt

      - name: Inject keys
        run: |
          echo -en '${{ secrets.KEYS_INI }}' >> keys.ini
          
      - name: Generate CLI docs
        run: |
          echo $PYTHONPATH
          export PYTHONPATH=$PYTHONPATH:.
          echo $PYTHONPATH
          typer cli.py utils docs --name wooster --output docs/source/cli.md

      - name: Commit updated read-me
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add docs/source/cli.md
          git commit --author="Prerit Das <preritdas@gmail.com>" -m "Update CLI documentation."
          git push
