name: cli docs

on:
  push:
    paths:
      - "cli.py"
  workflow_dispatch:
  
  
jobs:
  docs:
    runs-on: "ubuntu-latest"
    
    steps:
      - name: Checkout repository code
        uses: actions/checkout@v3
        
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"
        
      - name: Setup pip and typer-cli
        run: |
          pip install -U pip wheel
          pip install typer-cli
          
      - name: Install project dependencies
        run: |
          sed -i "/ta-lib==0.4.24/d" requirements.txt
          pip install -r requirements.txt
          
      - name: Display docs
        run: |
          echo $PYTHONPATH
          export PYTHONPATH=$PYTHONPATH:.
          echo $PYTHONPATH
          typer cli.py utils docs
