name: docs

on:
  push:
    paths:
      - "cli.py"
      - "README.md"
      - "docs/source/*"
  workflow_dispatch:
  pull_request:
  
  
jobs:
  docs:
    runs-on: self-hosted
    
    steps:
      - name: Checkout repository code
        uses: actions/checkout@v3
        
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Setup pip and typer-cli
        run: |
          pip install -U pip wheel
          pip install typer-cli
          
      - name: Install project dependencies
        run: |
          sed -i "/typer==0.6.1/d" requirements.txt
          sed -i "/ta-lib==0.4.24/d" requirements.txt
          pip install -r requirements.txt
          pip install ta-lib

      - name: Inject keys
        run: |
          echo -en '${{ secrets.KEYS_INI }}' >> keys.ini
          
      - name: Generate CLI docs
        run: |
          export PYTHONPATH=$PYTHONPATH:.
          typer cli.py utils docs --name wooster --output docs/source/cli.md
          sed -i "1 s/.*/# CLI Reference/" docs/source/cli.md

      - name: Build docs with sphinx
        run: |
          pip install -r docs/requirements.txt
          cd docs && make html && cd ..

      - name: Configure git
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
      
      - name: Commit updated CLI reference
        continue-on-error: true
        run: |
          git add docs/source/cli.md
          git commit --author="Prerit Das <preritdas@gmail.com>" -m "Update CLI documentation."

      - name: Commit updated doc build
        continue-on-error: true
        run: |
          git add docs/build/*
          git commit --author="Prerit Das <preritdas@gmail.com>" -m "Build documentation."

      - name: Push committed changes
        run: git push
