name: Tests

on: [push]

jobs:
  test:

    runs-on: ubuntu-latest

    steps:
      - name: Check out repository code
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install TA-Lib
        run: |
          sudo apt update && sudo apt upgrade -y
          sudo apt install wget -y
          sudo add-apt-repository ppa:deadsnakes/ppa
          sudo apt-get install build-essential -y
          sudo apt install python3.10-dev -y
          sudo apt-get install python3-dev -y
          wget http://prdownloads.sourceforge.net/ta-lib/ta-lib-0.4.0-src.tar.gz
          tar -xzf ta-lib-0.4.0-src.tar.gz
          cd ta-lib
          ./configure --prefix=/usr
          make
          sudo make install
          sudo apt update && sudo apt upgrade -y
          pip install ta-lib
          python -c "import talib"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip setuptools wheel
          pip install -r requirements.txt
          pip install pytest

      - name: Test with pytest
        run: |
          python -m pytest
