name: Tests

on: [push, pull_request]

jobs:
  test:

    strategy:
      fail-fast: false
      matrix:
        os: ["ubuntu-latest", "macos-latest"]

    runs-on: ${{ matrix.os }}

    steps:
      - name: Check out repository code
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install TA-Lib
        uses: knicknic/os-specific-run@v1.0.3
        with:
          linux: |
            sudo apt update && sudo apt upgrade -y
            sudo apt install wget -y
            sudo add-apt-repository ppa:deadsnakes/ppa
            sudo apt-get install build-essential -y
            sudo apt install python3.10-dev -y
            sudo apt-get install python3-dev -y
            wget http://prdownloads.sourceforge.net/ta-lib/ta-lib-0.4.0-src.tar.gz
            tar -xzf ta-lib-0.4.0-src.tar.gz
            cd ta-lib
            ./configure --prefix=/usr
            make
            sudo make install
            sudo apt update && sudo apt upgrade -y
          macos: |
            /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
            brew install ta-lib

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip setuptools wheel
          pip install -r requirements.txt
          pip install pytest

      - name: Inject keys
        uses: knicknic/os-specific-run@v1.0.3
        with:
          linux: |
            echo -en '[Finnhub]\napi_key = ${{ secrets.FINNHUB_API_KEY }}' >> keys.ini
          macos: |
            echo -en '[Finnhub]\napi_key = ${{ secrets.FINNHUB_API_KEY }}' >> keys.ini

      - name: Test with pytest
        run: |
          python -m pytest
